# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQTw2iE51kI3lm_8MzgCpQ3CrLY84Jt7
"""

!pip install pyTelegramBotAPI

import telebot
import csv
import os
from datetime import datetime, timedelta

TOKEN = '8263687452:AAHer-aV77fx6pfu1oCBmCdxLpYKB3DH0SA'
bot = telebot.TeleBot(TOKEN)
FILE = 'finance.csv'

categories = {
    'food': 'Food',
    'transport': 'Transport',
    'shopping': 'Shopping',
    'salary': 'Salary',
    'other': 'Other'
}

def create_file():
  if not os.path.exists(FILE):
    with open(FILE, 'w') as f:
      f.write('user,type,category,amount,date\n')
create_file()

def save(user, t_type, category, amount):
    with open(FILE, "a") as f:
        f.write(f"{user},{t_type},{category},{amount},{datetime.now()}\n")

def read(user):
    data = []
    with open(FILE, "r") as f:
        next(f)
        for line in f:
            u, t, c, a, d = line.strip().split(",")
            if str(user) == u:
                data.append((t, c, float(a), d))
    return data

@bot.message_handler(commands=['start'])
def start(msg):
    bot.send_message(msg.chat.id,
    "💸 Finance Bot\n\n"
    "/income - add income\n"
    "/expense - add expense\n"
    "/balance - show balance\n"
    "/daily - today report\n"
    "/weekly - weekly report")

@bot.message_handler(commands=['income'])
def income(msg):
    bot.send_message(msg.chat.id, "Enter amount and category (example: 5000 salary)")
    bot.register_next_step_handler(msg, process_income)

def process_income(msg):
    try:
        amount, category = msg.text.split()

        amount = float(amount)
        if amount <= 0:
            bot.send_message(msg.chat.id, "❌ Amount must be positive")
            return

        if category not in categories:
            category = "other"

        save(msg.chat.id, "income", category, amount)
        bot.send_message(msg.chat.id, "✅ Income saved")

    except:
        bot.send_message(msg.chat.id, "❌ Wrong format")

