# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQTw2iE51kI3lm_8MzgCpQ3CrLY84Jt7
"""

!pip install pyTelegramBotAPI

import telebot
import csv
import os
from datetime import datetime, timedelta

TOKEN = '8263687452:AAHer-aV77fx6pfu1oCBmCdxLpYKB3DH0SA'
bot = telebot.TeleBot(TOKEN)
FILE = 'finance.csv'

categories = {
    'food': 'Food',
    'transport': 'Transport',
    'shopping': 'Shopping',
    'salary': 'Salary',
    'other': 'Other'
}

def create_file():
  if not os.path.exists(FILE):
    with open(FILE, 'w') as f:
      f.write('user,type,category,amount,date\n')
create_file()

def save(user, t_type, category, amount):
    with open(FILE, "a") as f:
        f.write(f"{user},{t_type},{category},{amount},{datetime.now()}\n")

def read(user):
    data = []
    with open(FILE, "r") as f:
        next(f)
        for line in f:
            u, t, c, a, d = line.strip().split(",")
            if str(user) == u:
                data.append((t, c, float(a), d))
    return data

@bot.message_handler(commands=['start'])
def start(msg):
    bot.send_message(msg.chat.id,
    "💸 Finance Bot\n\n"
    "/income - add income\n"
    "/expense - add expense\n"
    "/balance - show balance\n"
    "/daily - today report\n"
    "/weekly - weekly report")
#adding income
@bot.message_handler(commands=['income'])
def income(msg):
    bot.send_message(msg.chat.id, "Enter amount and category (example: 5000 salary)")
    bot.register_next_step_handler(msg, process_income)

def process_income(msg):
    try:
        amount, category = msg.text.split()

        amount = float(amount)
        if amount <= 0:
            bot.send_message(msg.chat.id, "❌ Amount must be positive")
            return

        if category not in categories:
            category = "other"

        save(msg.chat.id, "income", category, amount)
        bot.send_message(msg.chat.id, "✅ Income saved")

    except:
        bot.send_message(msg.chat.id, "❌ Wrong format")

#adding expense
@bot.message_handler(commands=['expense'])
def expense(msg):
    bot.send_message(msg.chat.id, "Enter amount and category (example: 2000 food)")
    bot.register_next_step_handler(msg, process_expense)

def process_expense(msg):
    try:
        amount, category = msg.text.split()

        amount = float(amount)
        if amount <= 0:
            bot.send_message(msg.chat.id, "❌ Amount must be positive")
            return

        if category not in categories:
            category = "other"

        save(msg.chat.id, "expense", category, amount)
        bot.send_message(msg.chat.id, "✅ Expense saved")

    except:
        bot.send_message(msg.chat.id, "❌ Wrong format")
#balance
@bot.message_handler(commands=['balance'])

def balance(msg):
    data=read(msg.chat.id)
    
    income = 0
    expense = 0

    for t, c, a, d in data:
        if t == "income":
            income += a
        else:
            expense += a
    bot.send_message(msg.chat.id,
        f"💰 Income: {income}\n"
        f"💸 Expense: {expense}\n"
        f"📊 Balance: {income - expense}")
#addind daily report
@bot.message_handler(commands=['daily'])
def daily(msg):
    data = read(msg.chat.id)
    today = datetime.now().date()

    inc = 0
    exp = 0

    for t, c, a, d in data:
        d = datetime.fromisoformat(d).date()
        if d == today:
            if t == "income":
                inc += a
            else:
                exp += a

    bot.send_message(msg.chat.id,
        f"📅 Today\nIncome: {inc}\nExpense: {exp}\nBalance: {inc-exp}")

#adding weekly report
@bot.message_handler(commands=['weekly'])
def weekly(msg):
    data = read(msg.chat.id)
    week_ago = datetime.now() - timedelta(days=7)

    inc = 0
    exp = 0

    for t, c, a, d in data:
        d = datetime.fromisoformat(d)
        if d >= week_ago:
            if t == "income":
                inc += a
            else:
                exp += a

    bot.send_message(msg.chat.id,
        f"📊 Weekly\nIncome: {inc}\nExpense: {exp}\nBalance: {inc-exp}")

print("Bot is running...")
bot.polling()
