# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQTw2iE51kI3lm_8MzgCpQ3CrLY84Jt7
"""

!pip install pyTelegramBotAPI

import telebot
import csv
import os
from datetime import datetime, timedelta

TOKEN = '8263687452:AAHer-aV77fx6pfu1oCBmCdxLpYKB3DH0SA'
bot = telebot.TeleBot(TOKEN)
FILE = 'finance.csv'

categories = {
    'food': 'Food',
    'transport': 'Transport',
    'shopping': 'Shopping',
    'salary': 'Salary',
    'other': 'Other'
}

def create_file():
  if not os.path.exists(FILE):
    with open(FILE, 'w') as f:
      f.write('user,type,category,amount,date\n')
create_file()

def save(user, t_type, category, amount):
    with open(FILE, "a") as f:
        f.write(f"{user},{t_type},{category},{amount},{datetime.now()}\n")
